/**
 * Database Musuh Biasa dan 24 Boss Unik (Chapter 1-4, Act 1-6)
 */

export const ENEMY_TYPES = {
  // Regular Enemies
  goblin: {
    id: 'goblin',
    name: 'Goblin Runner',
    hp: 45,
    speed: 1.4,
    rewardGold: 12,
    rewardGems: 1,
    armor: 0,
    color: '#48bb78',
    size: 14,
    spriteKey: 'enemy_goblin',
    icon: '👺'
  },
  orc: {
    id: 'orc',
    name: 'Orc Warrior',
    hp: 110,
    speed: 0.9,
    rewardGold: 22,
    rewardGems: 1,
    armor: 4,
    color: '#38a169',
    size: 18,
    spriteKey: 'enemy_orc',
    icon: '👹'
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton Archer',
    hp: 75,
    speed: 1.1,
    rewardGold: 16,
    rewardGems: 1,
    armor: 1,
    color: '#e2e8f0',
    size: 15,
    spriteKey: 'enemy_skeleton',
    icon: '💀'
  },
  wolf: {
    id: 'wolf',
    name: 'Dire Wolf',
    hp: 60,
    speed: 1.9,
    rewardGold: 18,
    rewardGems: 1,
    armor: 0,
    color: '#a0aec0',
    size: 14,
    spriteKey: 'enemy_wolf',
    icon: '🐺'
  },
  bat: {
    id: 'bat',
    name: 'Shadow Bat',
    hp: 40,
    speed: 1.7,
    flying: true,
    rewardGold: 15,
    rewardGems: 1,
    armor: 0,
    color: '#9f7aea',
    size: 12,
    spriteKey: 'enemy_bat',
    icon: '🦇'
  },
  golem: {
    id: 'golem',
    name: 'Stone Golem',
    hp: 240,
    speed: 0.65,
    rewardGold: 40,
    rewardGems: 2,
    armor: 10,
    color: '#718096',
    size: 22,
    spriteKey: 'enemy_golem',
    icon: '🗿'
  },
  fire_elemental: {
    id: 'fire_elemental',
    name: 'Fire Sprite',
    hp: 140,
    speed: 1.2,
    rewardGold: 28,
    rewardGems: 2,
    armor: 2,
    color: '#f97316',
    size: 16,
    spriteKey: 'enemy_fire',
    icon: '🔥'
  },
  ice_wraith: {
    id: 'ice_wraith',
    name: 'Ice Wraith',
    hp: 170,
    speed: 1.0,
    rewardGold: 32,
    rewardGems: 2,
    armor: 5,
    color: '#38bdf8',
    size: 17,
    spriteKey: 'enemy_ice',
    icon: '👻'
  },
  void_crawler: {
    id: 'void_crawler',
    name: 'Void Crawler',
    hp: 280,
    speed: 1.15,
    rewardGold: 50,
    rewardGems: 3,
    armor: 8,
    color: '#a855f7',
    size: 20,
    spriteKey: 'enemy_void',
    icon: '👾'
  }
};

/**
 * 24 Boss Unik untuk Wave 15 di Setiap Act (Chapter 1-4, Act 1-6)
 */
export const BOSS_DATABASE = {
  // CHAPTER 1: Whispering Woods
  'ch1_act1': {
    id: 'goblin_king',
    name: 'Goblin King Grom',
    title: 'Penguasa Sarang Hutan Belantara',
    hp: 2200,
    speed: 0.7,
    rewardGold: 350,
    rewardGems: 75,
    armor: 5,
    color: '#22c55e',
    size: 28,
    spriteKey: 'boss_goblin_king',
    icon: '👑',
    ability: 'summon_minions',
    abilityCooldown: 6.0,
    description: 'Memanggil 3 Goblin Runner setiap 6 detik.'
  },
  'ch1_act2': {
    id: 'treant_ancient',
    name: 'Ancient Treant Barkhorn',
    title: 'Penjaga Pohon Terlarang',
    hp: 3400,
    speed: 0.5,
    rewardGold: 400,
    rewardGems: 85,
    armor: 12,
    color: '#15803d',
    size: 32,
    spriteKey: 'boss_treant',
    icon: '🌲',
    ability: 'regeneration',
    healRate: 45, // HP per second
    description: 'Memiliki regenerasi kulit kayu tebal yang menyembuhkan 45 HP/detik.'
  },
  'ch1_act3': {
    id: 'dire_alpha',
    name: 'Fenrir the Pack Leader',
    title: 'Raja Serigala Bulan Purnama',
    hp: 2800,
    speed: 1.3,
    rewardGold: 450,
    rewardGems: 95,
    armor: 4,
    color: '#475569',
    size: 28,
    spriteKey: 'boss_wolf',
    icon: '🐺',
    ability: 'speed_dash',
    dashCooldown: 5.0,
    description: 'Melesat dengan kecepatan 2.5x lipat secara berkala.'
  },
  'ch1_act4': {
    id: 'forest_witch',
    name: 'Morgana the Toxic Witch',
    title: 'Penyihir Rawa Racun',
    hp: 3800,
    speed: 0.65,
    rewardGold: 500,
    rewardGems: 105,
    armor: 6,
    color: '#9333ea',
    size: 26,
    spriteKey: 'boss_witch',
    icon: '🧙‍♀️',
    ability: 'magic_shield',
    shieldCooldown: 8.0,
    description: 'Menciptakan perisai sihir yang memblokir serangan selama 3 detik.'
  },
  'ch1_act5': {
    id: 'earth_golem',
    name: 'Terra Boulder Titan',
    title: 'Raksasa Batu Lembah Kuno',
    hp: 5200,
    speed: 0.45,
    rewardGold: 550,
    rewardGems: 120,
    armor: 18,
    color: '#78716c',
    size: 34,
    spriteKey: 'boss_earth_golem',
    icon: '🗿',
    ability: 'stun_towers',
    stunCooldown: 9.0,
    description: 'Menghentakkan tanah yang melumpuhkan tower terdekat selama 2.5 detik.'
  },
  'ch1_act6': {
    id: 'forest_dragon',
    name: 'Verdant Drake Lord Sylvan',
    title: 'Penguasa Puncak Bab 1',
    hp: 7500,
    speed: 0.7,
    rewardGold: 700,
    rewardGems: 200,
    armor: 10,
    color: '#059669',
    size: 36,
    spriteKey: 'boss_sylvan',
    icon: '🐉',
    ability: 'dragon_roar',
    abilityCooldown: 7.0,
    description: 'Mengaum meningkatkan speed dan membakar jalur pertempuran.'
  },

  // CHAPTER 2: Scorched Badlands
  'ch2_act1': {
    id: 'molten_berserker',
    name: 'Ignis the Rage Berserker',
    title: 'Prajurit Lahar Tak Terkendali',
    hp: 5500,
    speed: 0.8,
    rewardGold: 600,
    rewardGems: 110,
    armor: 8,
    color: '#dc2626',
    size: 28,
    spriteKey: 'boss_berserker',
    icon: '🪓',
    ability: 'berserk_frenzy',
    description: 'Mendapat +60% kecepatan bergerak saat HP di bawah 40%.'
  },
  'ch2_act2': {
    id: 'ash_phantom',
    name: 'Cinder Shadow',
    title: 'Hantu Abu Vulkanik',
    hp: 6200,
    speed: 0.95,
    rewardGold: 650,
    rewardGems: 125,
    armor: 6,
    color: '#ea580c',
    size: 27,
    spriteKey: 'boss_phantom',
    icon: '🌫️',
    ability: 'smoke_screen',
    description: 'Mengurangi akurasi serangan tower sebesar 35% di jalurnya.'
  },
  'ch2_act3': {
    id: 'magma_wurm',
    name: 'Gorgoroth the Magma Wurm',
    title: 'Cacing Penggali Lahar Inti',
    hp: 7800,
    speed: 0.6,
    rewardGold: 700,
    rewardGems: 140,
    armor: 14,
    color: '#b91c1c',
    size: 32,
    spriteKey: 'boss_wurm',
    icon: '🐛',
    ability: 'burrow_armor',
    description: 'Mengeraskan sisik lahar untuk menahan 50% damage selama 4 detik.'
  },
  'ch2_act4': {
    id: 'fire_djinn',
    name: 'Ifrit Sunbringer',
    title: 'Penghulu Jin Api Gurun Pasir',
    hp: 8800,
    speed: 0.85,
    rewardGold: 780,
    rewardGems: 155,
    armor: 8,
    color: '#f59e0b',
    size: 30,
    spriteKey: 'boss_djinn',
    icon: '🧞',
    ability: 'summon_fire_sprites',
    description: 'Memanggil 2 Fire Sprite yang bergerak sangat cepat.'
  },
  'ch2_act5': {
    id: 'obsidian_colossus',
    name: 'Obsidian Juggernaut',
    title: 'Benteng Berjalan Kaca Hitam',
    hp: 11000,
    speed: 0.45,
    rewardGold: 850,
    rewardGems: 175,
    armor: 22,
    color: '#1c1917',
    size: 36,
    spriteKey: 'boss_obsidian',
    icon: '⬛',
    ability: 'damage_reduction',
    description: 'Memantulkan sebagian serangan kembali dan kebal terhadap stun/freeze.'
  },
  'ch2_act6': {
    id: 'volcanic_hydra',
    name: 'Pyroclast the Nine-Headed',
    title: 'Penguasa Puncak Bab 2',
    hp: 14000,
    speed: 0.65,
    rewardGold: 1000,
    rewardGems: 300,
    armor: 12,
    color: '#ef4444',
    size: 38,
    spriteKey: 'boss_hydra',
    icon: '🐲',
    ability: 'hydra_split',
    description: 'Saat terbunuh, terpecah menjadi 2 Hydra Spawn yang lebih gesit.'
  },

  // CHAPTER 3: Frostbite Peaks
  'ch3_act1': {
    id: 'frost_yeti',
    name: 'Ymir the Avalanche Yeti',
    title: 'Monster Salju Gua Gletser',
    hp: 10500,
    speed: 0.6,
    rewardGold: 850,
    rewardGems: 150,
    armor: 12,
    color: '#0284c7',
    size: 30,
    spriteKey: 'boss_yeti',
    icon: '❄️',
    ability: 'freeze_aura',
    description: 'Memperlambat laju tembakan tower sekitar sebesar 25%.'
  },
  'ch3_act2': {
    id: 'ice_queen',
    name: 'Glacia the Ice Empress',
    title: 'Ratu Takhta Kristal Es',
    hp: 12500,
    speed: 0.75,
    rewardGold: 920,
    rewardGems: 170,
    armor: 10,
    color: '#38bdf8',
    size: 28,
    spriteKey: 'boss_ice_queen',
    icon: '👑',
    ability: 'blizzard_shield',
    description: 'Menciptakan badai salju penangkal proyektil selama 3.5 detik.'
  },
  'ch3_act3': {
    id: 'frostwyrm',
    name: 'Sindragosa the Rime Drake',
    title: 'Naga Tulang Pembawa Badai Kutub',
    hp: 15000,
    speed: 0.8,
    rewardGold: 1000,
    rewardGems: 190,
    armor: 14,
    color: '#bae6fd',
    size: 35,
    spriteKey: 'boss_frostwyrm',
    icon: '🐉',
    ability: 'glacial_breath',
    description: 'Membekukan tower selama 3 detik dalam radius lintasan terbang.'
  },
  'ch3_act4': {
    id: 'abominable_drake',
    name: 'Boreas the Storm Dreadnought',
    title: 'Panglima Perang Gletser Purba',
    hp: 17500,
    speed: 0.55,
    rewardGold: 1100,
    rewardGems: 210,
    armor: 18,
    color: '#0369a1',
    size: 34,
    spriteKey: 'boss_drake',
    icon: '🧊',
    ability: 'shatter_ice',
    description: 'Menembakkan paku es tajam yang membatalkan buff tower.'
  },
  'ch3_act5': {
    id: 'glacial_titan',
    name: 'Thrym the Frost Monarch',
    title: 'Raja Titan Es Abadi',
    hp: 21000,
    speed: 0.45,
    rewardGold: 1250,
    rewardGems: 240,
    armor: 24,
    color: '#0c4a6e',
    size: 38,
    spriteKey: 'boss_glacial_titan',
    icon: '🏔️',
    ability: 'avalanche',
    description: 'Memanggil longsoran salju yang memberikan perisai 2000 HP.'
  },
  'ch3_act6': {
    id: 'frost_sovereign',
    name: 'Kaelith Absolute Zero',
    title: 'Penguasa Puncak Bab 3',
    hp: 26000,
    speed: 0.65,
    rewardGold: 1500,
    rewardGems: 400,
    armor: 16,
    color: '#e0f2fe',
    size: 40,
    spriteKey: 'boss_frost_sovereign',
    icon: '⭐',
    ability: 'winter_stasis',
    description: 'Memasuki kondisi stasis beku tak terkalahkan selama 3 detik sambil memulihkan HP.'
  },

  // CHAPTER 4: Abyssal Realm
  'ch4_act1': {
    id: 'void_stalker',
    name: 'Malzahar the Void Shifter',
    title: 'Pemburu Dimensi Kehampaan',
    hp: 22000,
    speed: 1.1,
    rewardGold: 1300,
    rewardGems: 250,
    armor: 10,
    color: '#7c3aed',
    size: 28,
    spriteKey: 'boss_void_stalker',
    icon: '👁️',
    ability: 'teleport_dash',
    description: 'Melakukan warp teleport 60 pixel ke depan secara tiba-tiba.'
  },
  'ch4_act2': {
    id: 'chaos_harbinger',
    name: 'Nihilus the Entropy Lord',
    title: 'Pemberi Kutukan Kekacauan',
    hp: 27000,
    speed: 0.75,
    rewardGold: 1450,
    rewardGems: 280,
    armor: 14,
    color: '#6b21a8',
    size: 32,
    spriteKey: 'boss_chaos',
    icon: '🔮',
    ability: 'hex_curse',
    description: 'Mengutuk tower dengan DPS tertinggi untuk berhenti menembak selama 4 detik.'
  },
  'ch4_act3': {
    id: 'shadow_leviathan',
    name: 'Ouroboros the Void Leviathan',
    title: 'Ular Kosmik Pemakan Cahaya',
    hp: 33000,
    speed: 0.7,
    rewardGold: 1600,
    rewardGems: 310,
    armor: 16,
    color: '#581c87',
    size: 36,
    spriteKey: 'boss_leviathan',
    icon: '🐍',
    ability: 'hp_leech',
    description: 'Menyerap 1% HP maksimum setiap kali terkena 10 serangan.'
  },
  'ch4_act4': {
    id: 'eclipse_devourer',
    name: 'Umbra the Dark Eclipse',
    title: 'Gerhana Abadi Penghancur Tata Surya',
    hp: 40000,
    speed: 0.65,
    rewardGold: 1800,
    rewardGems: 350,
    armor: 20,
    color: '#3b0764',
    size: 36,
    spriteKey: 'boss_eclipse',
    icon: '🌑',
    ability: 'blackout',
    description: 'Menghalangi jarak tembak semua tower sebesar 30%.'
  },
  'ch4_act5': {
    id: 'singularity_master',
    name: 'Aethelgard the Rift Maker',
    title: 'Pencipta Gravitasi Supermasif',
    hp: 48000,
    speed: 0.55,
    rewardGold: 2100,
    rewardGems: 400,
    armor: 22,
    color: '#4c1d95',
    size: 38,
    spriteKey: 'boss_singularity',
    icon: '🌌',
    ability: 'gravity_warp',
    description: 'Menciptakan lubang gravitasi yang melindungi diri dari proyektil.'
  },
  'ch4_act6': {
    id: 'nexus_sovereign',
    name: 'Omega Cosmic Primordial',
    title: 'Penguasa Tertinggi Seluruh Babak Game',
    hp: 65000,
    speed: 0.6,
    rewardGold: 3000,
    rewardGems: 1000,
    armor: 25,
    color: '#00f5d4',
    size: 42,
    spriteKey: 'boss_omega',
    icon: '👑👾',
    ability: 'apocalypse_phase',
    description: 'Final Boss Utama! Memiliki perisai kosmik, regenerasi HP, dan memanggil minion elit.'
  }
};

/**
 * Helper untuk mendapatkan Boss config dari Chapter dan Act
 */
export function getBossData(chapterId, actIndex) {
  const key = `ch${chapterId}_act${actIndex}`;
  return BOSS_DATABASE[key] || BOSS_DATABASE['ch1_act1'];
}
